version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=api
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: bikefinder
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

  json-server:
    container_name: json-server-container
    image: json-server-image
    build: ./src/database
    ports: 
      - "3000:3000"
    volumes:
      - ./src/database/estacoes.json:/data/estacoes.json
    command: json-server --watch /data/estacoes.json --host 0.0.0.0

volumes:
  pgdata:
    driver: local