name: Complete Workflow

on: ['push']

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        postgres-version: [14.0]
    
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Start Postgres
        uses: actions/checkout@v2
        with:
          postgres-version: ${{ matrix.postgres-version }}
      
      - name: Install dependencies
        run: yarn --frozen-lockfile